name: CaptureTheWool
main: com.gmail.lynx7478.ctw.CTW
authors: [muresame, DaddyJGG]
description: Capture the wool minigame plugin.
version: 2.2
commands:
  mapbuilder:
    description: Opens the mapbuilder.
  team:
    description: Joins a team.
  ctw:
    description: CTW main command.
  roles:
    description: Role command.
  afk:
    description: AFK command.