name: CaptureTheWool
main: com.gmail.lynx7478.ctw.CTW
author: Yuumiheim
description: Capture the wool minigame plugin.
version: 2.2
commands:
   team:
     description: Joins a team.
   ctw:
     description: CTW main command.
   roles:
     description: Role command.
   afk:
     description: AFK command.